name: docserver
version: "1.1"
summary: "An office suite that allowing to create, view and edit documents."
description: "ONLYOFFICE docserver"
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18
architectures:
  - amd64

apps:
  docserver:
    adapter: full
    command: bin/start
    plugs:
      - home
      - desktop
      - desktop-legacy


  node:
    command: bin/node
    adapter: full
  
  nginx:
    command: whereis nginx
    plugs: [network, network-bind]


parts:  
  docserver:
    plugin: dump
    source: snap/onlyoffice-documentserver-ie_5.3.4-3_amd64.deb
    source-type: deb
    stage-packages:
      - libcurl3
      - libxml2
      - supervisor
      - fonts-dejavu
      - fonts-liberation
      - ttf-mscorefonts-installer
      - fonts-crosextra-carlito
      - fonts-takao-gothic
      - fonts-opensymbol
      - create-resources
    override-build: |
      rm -f lib/libicuuc.so.58
      rm -f lib/libPdfWriter.so
      rm -f lib/libdoctrenderer.so
      rm -f lib/libHtmlFile.so
      rm -f lib/libHtmlRenderer.so
      rm -f lib/libPdfReader.so
      rm -f lib/libkernel.so
      rm -f lib/libXpsFile.so
      rm -f lib/libDjVuFile.so
      rm -f lib/libUnicodeConverter.so
      rm -f lib/libicudata.so.58
      rm -f lib/libgraphics.so
      snapcraftctl build
      # edition supervisor/* && /supervisord.conf ds-example.conf
      sed -i -e 's/\/var\/www/%(ENV_SNAP)s\/var\/www/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/supervisor/*
      sed -i -e 's/\/etc/%(ENV_SNAP)s\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/supervisor/*
      sed -i -e 's/\/var\/log/%(ENV_SNAP_USER_COMMON)s\/var\/log/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/supervisor/*
      sed -i -e 's/\/var/\/home\/igor\/snap\/docserver\/common\/var/g' $SNAPCRAFT_PART_INSTALL/etc/supervisor/supervisord.conf
      sed -i -e 's/etc/%(ENV_SNAP)s\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/supervisor/supervisord.conf
      sed -i -e 's/\/var\/www/%(ENV_SNAP)s\/var\/www/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/supervisor/ds-example.conf
      sed -i -e 's/\/etc/%(ENV_SNAP)s\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/supervisor/ds-example.conf
      sed -i -e 's/\/var\/log/%(ENV_SNAP_USER_COMMON)s\/var\/log/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/supervisor/ds-example.conf
      sed -i -e 's/user=ds/;user=ds/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/supervisor/*
      sed -i -e 's/user=ds/;user=ds/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/supervisor/*
      # edition production-linux.json 
      #sed -i -e 's/var\/www/snap\/docserver\/current\/var\/www/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/production-linux.json 
      #sed -i -e 's/var\/lib/snap\/docserver\/current\/var\/lib/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/production-linux.json 
      #sed -i -e 's/etc/snap\/docserver\/current\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/production-linux.json
      #sed -i -e 's/usr/snap\/docserver\/current\/usr/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/production-linux.json
      #sed -i -e 's/web-apps\/vendor/snap\/docserver\/current\/var\/www\/onlyoffice\/documentserver\/web-apps\/vendor/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/production-linux.json
      # edition etc/onlyoffice/documentserver/nginx/ds...
      sed -i -e 's/etc/snap\/docserver\/current\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/nginx/ds.conf
      sed -i -e 's/etc/snap\/docserver\/current\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/nginx/ds.conf.tmpl
      sed -i -e 's/etc/snap\/docserver\/current\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/nginx/ds-ssl.conf.tmpl
      sed -i -e 's/var\//home\/igor\/snap\/docserver\/common\/var\//g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/nginx/includes/ds-common.conf
      sed -i -e 's/var/snap\/docserver\/current\/var/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf
      sed -i -e 's/var/snap\/docserver\/current\/var/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/nginx/includes/ds-example.conf
      # edition init.d/supervisor
      sed -i -e 's/usr\/sbin\/nginx/snap\/docserver\/current\/usr\/sbin\/nginx/g' $SNAPCRAFT_PART_INSTALL/etc/init.d/supervisor
      sed -i -e 's/etc/snap\/docserver\/current\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/init.d/supervisor
      sed -i -e 's/lib/snap\/docserver\/current\/lib/g' $SNAPCRAFT_PART_INSTALL/etc/init.d/supervisor
      sed -i -e 's/var/home\/igor\/snap\/docserver\/common\/var/g' $SNAPCRAFT_PART_INSTALL/etc/init.d/supervisor
      # edition documentserver && documentserver-example
      mv $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/production-linux.json $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/production-linux.json-old
      mv $SNAPCRAFT_PART_INSTALL/etc/supervisor/conf.d/ds-example.conf $SNAPCRAFT_PART_INSTALL/etc/supervisor/conf.d/ds-example.conf-old
      sed -i -e 's/web-apps/snap\/docserver\/current\/var\/www\/onlyoffice\/documentserver\/web-apps/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/default.json
      #sed -i '4d' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/production-linux.json
      #sed -i -e 's/"siteUrl"':' "\/",/"port"':' 2000,\n    "siteUrl"':' "http':'\/\/127.0.0.1:8000\/",\n     "apiUrl"':' "snap\/docserver\/current\/var\/www\/onlyoffice\/documentserver\/web-apps\/apps\/api\/documents\/api.js",\n    "preloaderUrl"':' "snap\/docserver\/current\/var\/www\/onlyoffice\/documentserver\/web-apps\/apps\/api\/documents\/cache-scripts.html"/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/production-linux.json
      mkdir -p $SNAPCRAFT_PART_INSTALL/var/www/onlyoffice/documentserver-example/public/files
      mkdir -p $SNAPCRAFT_PART_INSTALL/var/www/onlyoffice/documentserver-example/public/files/__1
      ###
      #ln -s $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/nginx/conf.d/ds.conf $SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d/ds.conf
      #sed -i -e 's/"files/"home\/igor\/snap\/docserver\/common\/var\/lib\/onlyoffice\/documentserver-example\/public\/files/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/default.json
      #sed -i -e 's/.\/public/home\/igor\/snap\/docserver\/common\/var\/lib\/onlyoffice\/documentserver-example\/public/g' $SNAPCRAFT_PART_INSTALL/var/www/onlyoffice/documentserver-example/app.js
      #sed -i -e 's/"path"':' "public"/"path"':' "home\/igor\/snap\/docserver\/common\/var\/lib\/onlyoffice\/documentserver-example\/public"/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/default.json
      #sed -i '28,33d' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/default.json
      #sed -i -e 's/80/1200/g' $SNAPCRAFT_PART_INSTALL/etc/nginx/sites-available/default
      #sed -i -e 's/"directory": "\/var/"directory": "\/home\/igor\/snap\/docserver\/common\/var/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/production-linux.json 
      #sed -i -e 's/"folderPath": "\/var/"folderPath": "\/home\/igor\/snap\/docserver\/common\/var/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/production-linux.json 
      # copy lib
      cp $SNAPCRAFT_PART_INSTALL/var/www/onlyoffice/documentserver/server/FileConverter/bin/*.so $SNAPCRAFT_PART_INSTALL/lib/
  node:
    plugin: dump
    source: https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-x64.tar.gz

  nginx:
    plugin: dump
    source: snap/nginx_1.13.9-1~xenial_amd64.deb
    source-type: deb
    override-build: |
      rm -f etc/nginx/modules
      snapcraftctl build
      sed -i -e 's/etc/snap\/docserver\/current\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/nginx/nginx.conf
      sed -i -e 's/var/home\/igor\/snap\/docserver\/common\/var/g' $SNAPCRAFT_PART_INSTALL/etc/nginx/nginx.conf
      ###sed -i -e 's/run/home\/igor\/snap\/docserver\/common\/run/g' $SNAPCRAFT_PART_INSTALL/etc/nginx/nginx.conf
      ##mv $SNAPCRAFT_PART_INSTALL/etc/nginx/nginx.conf $SNAPCRAFT_PART_INSTALL/etc/nginx/nginx.conf-old
      #sed -i -e 's/usr\/sbin\/nginx/snap\/docserver\/current\/usr\/sbin\/nginx/g' $SNAPCRAFT_PART_INSTALL/etc/init.d/nginx
      #sed -i -e 's/etc/snap\/docserver\/current\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/init.d/nginx
      #sed -i -e 's/lib/snap\/docserver\/current\/lib/g' $SNAPCRAFT_PART_INSTALL/etc/init.d/nginx
      #sed -i -e 's/run/home\/igor\/snap\/docserver\/common\/run/g' $SNAPCRAFT_PART_INSTALL/etc/init.d/nginx
      #
      #sed -i -e 's/var/home\/igor\/snap\/docserver\/common\/var/g' $SNAPCRAFT_PART_INSTALL/etc/logrotate.d/nginx
      #sed -i -e 's/etc/snap\/docserver\/current\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/logrotate.d/nginx
      #sed -i -e 's/var\/run/home\/igor\/snap\/docserver\/common\/var\/run/g' $SNAPCRAFT_PART_INSTALL/lib/systemd/system/nginx.service
      #sed -i -e 's/usr\/sbin\/nginx/snap\/docserver\/current\/usr\/sbin\/nginx/g' $SNAPCRAFT_PART_INSTALL/lib/systemd/system/nginx.service
      sed -i -e 's/80/2000/g' $SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d/default.conf
      sed -i -e 's/usr/snap\/docserver\/current\/usr/g' $SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d/default.conf
      #rm $SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d/default.conf
      cp /root/parts/docserver/install/etc/onlyoffice/documentserver/nginx/ds.conf $SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d/ds.conf
      sed -i -e 's/80/2000/g' $SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d/ds.conf
      



  starter:
    plugin: dump
    source: snap/config
    organize:
      start: bin/start
      production-linux.json: etc/onlyoffice/documentserver/production-linux.json
      ds-example.conf: etc/supervisor/conf.d/ds-example.conf
      #nginx.conf: etc/nginx/nginx.conf
      fastcgi.conf: etc/nginx/fastcgi.conf
      proxy_params: etc/nginx/proxy_params

