#!/bin/bash
user=postgres
#	if grep $user /etc/passwd then
#		echo "The user $user Exists"
#	else
#		adduser --quiet $user
#	fi

#sudo snap restart docserver
#su - $user

#docserver.initialize initdb

#/snap/docserver/x1/usr/bin/pg_ctl -D /home/postgres/snap/docserver/common/data -l logfile start
su - postgres -c 'docserver.confdb'
/snap/docserver/current/script2